### ISSUE TITLE
Document patterns

### ISSUE THREAD

**Issue by carllerche** [tower-rs/tower#105]
We have built up a number of patterns that were developed from our usage of Tower. We should document these.

This is a meta issue to track the patterns that should get documented.

* [ ] Use `Service + Clone` to allow moving an inner service into a response future.
* [ ] Implement `Service` for `Arc<MyType>` to get around `&mut` requirement.

cc/ @seanmonstar, @olix0r, @hawkw: I'm sure I'm forgetting patterns here. Thoughts?

**Comment by davidbarsky** [comment]
I'm thinking that a story around end-to-end testing, in the vein [that tower-web](https://github.com/carllerche/tower-web/blob/master/tests/resource.rs) approaches it, would be a useful thing to document and provide.

**Comment by carllerche** [comment]
Consolidating with #33.
