### ISSUE TITLE
Consider Approaches to Borrowed Data in `Service`

### ISSUE THREAD

**Issue by cramertj** [tower-rs/tower#106]
The basic idea is that `Service` implementations may have a `Response` value that contains references, rather than owned data. https://github.com/tower-rs/tower/issues/99 would make it possible to have the `type Response` depend on lifetimes in the `Request` type parameter, and so would allow `Response` to reference the `Request` object, which gets us part of the way. However, there still wouldn't be a way to reference items created inside the `Future` returned from `call`, and if the `Request` was owned (no lifetimes) there wouldn't be a way to return references into it, only owned objects that contain bits from it. If `call` wants to do e.g. zero-copy parsing using serde/nom and then return the parsed object/AST (which references the `Request` buffer), this still wouldn't be possible.

One solution that I've been using in Fuchsia is to sort of CPS-transform the request-response pattern, allowing the `Service` implementation to call into whatever is receiving the `Response`. Applied to the `Service` trait (and using GATs), this could look something like this:

```rust
trait Service<Request, Responder: for<'a> Sink<Self::Response<'a>>> {
    type Response<'a>;
    type Error;
    type Future: Future<Item = (), Error = Self::Error>;
    fn poll_ready(&mut self) -> Poll<(), Self::Error>;
    fn call(&mut self, req: Request, res: Responder) -> Self::Future;
}

// Example impl:
impl<Buf, Responder> Service<Buf, Responder>,  for BorrowedJsonTyDeserializer
where
    Buf: AsRef<[u8]>
    Responder: for<'a> Sink<Self::Response<'a>>
{
    type Response<'a> = BorrowedJsonTy<'a>;
    type Error = io::Error;
    exists type Future: Future<Item = (), Error = Self::Error>;
    fn poll_ready(&mut self) -> Poll<(), Self::Error> { Poll::Ready(()) }
    fn call(&mut self, req: Buf, res: Responder) -> Self::Future {
        async move {
            await!(res.send(BorrowedJsonTy::from_slice(req.as_ref())?)?)
        }
    }
}
```

Obviously this is pretty fuzzy and relies on a feature (GATs) that isn't implemented yet, but I think it gets across the general idea of what I'm trying to achieve.

Another related transformation that we do in Fuchsia is to model most request/response patterns as `Stream`s that yield a `(req, response_channel)` pair, which makes explicit backpressure like `poll_ready` unnecessary, as the code processing the stream gets to choose how often to pull items off. If you wish to process up to 100 elements at a time, you can do something like `request_stream.for_each_concurrent(|(req, res)| ...res.send(...) ... )`. This pattern works out really well for us and is often more ergonomic than trying to make a trait like `Service` fit into the equation. The `res.send(...)` methods we use frequently take references (including trait objects) which isn't possible with the current `Service` trait.

Please let me know if y'all have other ideas about how to allow these types of borrowed messages. I'm hopeful that together we can come up with a way to allow ergonomic borrowed response objects like this.

cc @aturon @carllerche 

P.S. One thing that comes up often is that the `res` objects all want to write into a shared resource, e.g. a `TcpSocket`. This works out naturally in the "return a `Response` object" formulation because the thing calling `Service::call` can choose when to push objects into the socket in series, but in the CPS formulation is a bit trickier since you have to notify each writer in turn when the socket is readable and it's that particular writer's turn to complete. This requires some more clever wakeup logic that would be nice to get rid of ;)

**Comment by aturon** [comment]
There's a lot to think about here, but one thing that strikes me is: if we *do* find a good solution to this problem, it should be possible to introduce it without *too* much disruption, because existing `Service` implementations should be trivially transformable to the CPS'ed version. (Could do this via a blanket impl etc). Does that seem right? If so, I think it eliminates any urgency here.

**Comment by cramertj** [comment]
@aturon Yep, it'd be easy to wrap the current `Service::call` in a `res.send(Service::call(req))`. The blanket impl only makes sense in that direction, though, so middleware based around `Service` wouldn't be trivially compatible with `NewService`.

**Comment by seanmonstar** [comment]
Passing a `Sink` to as responder may be a separate topic from borrowing (or maybe its the only kind of borrowing you'd want?), but I'll comment about it specifically: the idea of `Service` is to serve RPC, where you have a single response for a request. A `Sink` implies being able to to send multiple items back. I suppose an item *could* implement `Sink` and only be allowed to send a single item, but then we've moved that constraint from compile-time to run-time.

**Comment by aturon** [comment]
@seanmonstar For HTTP, think about response bodies, where you might produce the body in a series of chunks -- much like the `BufStream` trait  in tower-web.

**Comment by seanmonstar** [comment]
@aturon I don't quite see the connection there. Do you mean if it were `Sink<ResOrBuf<B>>` with `enum ResOrBuf<B> { Res(Response<()>), Buf(B), }`?

**Comment by cramertj** [comment]
@seanmonstar Good call-- `Sink` isn't exactly what you want-- it's really `trait Send<T, E> { async fn send(self, T) -> Result<T, E>; }` or something.

**Comment by carllerche** [comment]
I don't believe there currently are any actions to take from this issue, so I'm going to close it. Please let me know if this is an incorrect conclusion.
