### ISSUE TITLE
Stupid question: what's the means of add lifetime bound after trait name?

### ISSUE THREAD

**Issue by ariesdevil** [tower-rs/tower#107]
ref: https://github.com/tower-rs/tower/blob/b95c8d103056d9876b80b856b5f76754bf0f7b85/tower-router/src/lib.rs#L24

**Comment by hawkw** [comment]
@ariesdevil that means that types implementing the trait must be valid for the specified lifetime (in this case, the `'static` lifetime).

FYI, this syntax also allows you to specify any valid type bounds on the implementors of a trait. For example: 
```rust
trait Food { }
trait Fruit: Food { }
    
struct Apple;
impl Food for Apple { }
// This compiles
impl Fruit for Apple { }

struct Pear;
// This won't compile, as `Pear` doesn't implement `Fruit`.
impl Fruit for Pear { }
```
(Playground link: https://play.rust-lang.org/?gist=bc9f7c94dbdaef0864f94dcc9b49a951&version=stable&mode=debug&edition=2015)

**Comment by ariesdevil** [comment]
Crystal answer, thanks very!
