### ISSUE TITLE
Speculative Execution Service

### ISSUE THREAD

**Issue by danburkert** [tower-rs/tower#15]
For idempotent services, it can be useful to issue speculative requests to alternate replicas when the original request is slow in completing. This can smooth over latency outliers at the cost of wasted execution.  For an example from a real world system, see the [HDFS 'hedged reads' feature](https://issues.apache.org/jira/browse/HDFS-5776).  This relates to #14, since you typically want to design the retry and speculative execution policies in tandem.

**Comment by carllerche** [comment]
Is this #192?

**Comment by neoeinstein** [comment]
It certainly looks like this is closed by #192.

**Comment by carllerche** [comment]
Closing :+1:
