### ISSUE TITLE
Example of TCP client server

### ISSUE THREAD

**Issue by rohitjoshi** [tower-rs/tower#179]
Can we have simple example/doc on tcp client server communication using tower and how to integrate reconnect, rate limit etc modules?

**Comment by carllerche** [comment]
There are some examples added here: https://github.com/tower-rs/tower/blob/master/tower/examples/client.rs

👍

**Comment by rohitjoshi** [comment]
These are Http based on hyper. I would appreciate simple tcp echo server and client

**Comment by carllerche** [comment]
We will have more once tokio-tower is more ready.
