### ISSUE TITLE
Should `Filter` define a `Predicate` trait, or should it use `Service`?

### ISSUE THREAD

**Issue by carllerche** [tower-rs/tower#183]
A "predicate" can be any service that has a response of `()` and `filter::Error` error type.

Does the `Predicate` hold its weight?

**Comment by LucioFranco** [comment]
I am in favor of keeping the trait, I feel making it a service will be just confusing. The other options is we could just accept a `Fn`?

**Comment by carllerche** [comment]
All signs point to no.
