### ISSUE TITLE
A Server(?) abstraction?

### ISSUE THREAD

**Issue by withoutboats** [tower-rs/tower#20]
Does it make sense to provide an abstraction for the other side of the NewService handshake - the trait implemented by various protocol server implementations?

Something like this?

```rust
trait NewServer {
    type Request;
    type Response;
    type Error;
    type Server;
    fn bind<S>(&self, new_service: S) -> Result<Self::Server, Self::Error>
         where S: NewService<Request = Self::Request, Response = Self::Response, Error = Self::Error>;
}
```

**Comment by carllerche** [comment]
I believe there are traits that cover the cases.
