### ISSUE TITLE
Consider renaming `ServiceBuilder::build_service` -> `service`

### ISSUE THREAD

**Issue by carllerche** [tower-rs/tower#226]
The type is already named "builder". Including `build` as a prefix to the fn name feels like a stutter.

I would propose renaming the fn -> `service(...)` and rename `build_make_service` -> `make_service(...)`.

**Comment by seanmonstar** [comment]
I like shortening the "build" name as well.

**Comment by carllerche** [comment]
@seanmonstar I would default to `build` as the fn name except in this case there are more than one types that can be built. So, instead of dropping the "thing" being built, i am proposing dropping "build"

**Comment by seanmonstar** [comment]
I agree and was thinking exactly the same: `build` is fine when it's the only thing, but we have 2 things that can be built.

**Comment by LucioFranco** [comment]
Yeah, I'm fine with this pattern as long as we have good examples to tell people what fn actually will produce the final build value.
