### ISSUE TITLE
Audit API

### ISSUE THREAD

**Issue by carllerche** [tower-rs/tower#230]
A general issue tracking the need to do an audit pass of all APIs before releasing 0.1.

- [x] Remove `reconnect` re-export
- [x] Remove `ServiceBuilder::make_service()`
- [x] `doc(inline)` the re-exports
- [ ] double check we're OK with `retry` API

**Comment by jonhoo** [comment]
I assume this can be closed?

**Comment by LucioFranco** [comment]
We already released a 0.1 so this should be closed.
