### ISSUE TITLE
Consider a blanket Service Impl for Fn

### ISSUE THREAD

**Issue by davidbarsky** [tower-rs/tower#232]
It might be nice to be able to write something like:

```rust
fn call<T>(req: Request<T>) -> impl Future<Item = Response<T>, Error = Error> {
   ...
}
```

...and have it be treated as a valid service.

**Comment by carllerche** [comment]
Unfortunately, this does not work due to coherence limitations.

**Comment by seanmonstar** [comment]
This is similar to finagle's `Service.mk` and tower's `service_fn`. Maybe we could make it even easier to make one?

**Comment by davidbarsky** [comment]
@seanmonstar I forgot about Tower's `ServiceFn` when writing this issue. I'm not sure how it could made even easier—some sort of macro?

**Comment by seanmonstar** [comment]
I dunno, it kinda feels like an extra or strange import, versus in finagle it's just `Service.mk { req => res }`...

**Comment by carllerche** [comment]
@seanmonstar what change are you proposing?

**Comment by seanmonstar** [comment]
I hadn't proposed anything yet... I think have a static function on `Service` could be cool, but maybe not yet...
