### ISSUE TITLE
util: Service/Layer map

### ISSUE THREAD

**Issue by LucioFranco** [tower-rs/tower#243]
A service to map the request type within a stack of services. This should provide the ability maybe just for now to sync or async change the request type of a service stack.

**Comment by davidbarsky** [comment]
Does this entail supporting multiple request types per service/stack, instead of the one-per-service model we have at the moment?

**Comment by carllerche** [comment]
There were map and map_err combinators. That was pre- `ServiceBuilder`. We should figure out the best way to re-introduce this.

**Comment by jonhoo** [comment]
I assume this is a duplicate of #272?

**Comment by LucioFranco** [comment]
👍 I have an implementation of this for vector I can bring it over if you want to assign me the correct issue.

**Comment by jonhoo** [comment]
Closing as a dupe, and making #272 the main issue.
