### ISSUE TITLE
Dynamic Configuration of downstream layers

### ISSUE THREAD

**Issue by drusellers** [tower-rs/tower#255]
I am starting work on a new proxy at work, and one feature we need to implement is the ability to have what we are calling internally "a tower in a tower". To us this means that we would have a root `tower_hyper::server::Server` that would have an initial collection of layers to process things, and then in the final `tower::Service` we would build another `tower_hyper::server::Server` using data out of the request headers and then pass the request to this new nested server.

1. Is there a better place to ask this question?
2. Is it possible now, or a goal of the future, to pass an inflight request to a new tower/server?
3. If not, is there a better way to approach per request configuration of layers?

**Comment by LucioFranco** [comment]
@drusellers do you actually need another http server or are you looking to have another service stack to process the request? Both should be possible, you most likely will want to spawn a future to handle the second server but really depends what your goal is.

**Comment by drusellers** [comment]
@LucioFranco I don't need another http server, another "service stack" is probably what I'm looking for. At this point, i'm looking for the "right" language to communicate things. 

So, in the case of "service stack" what I want is to have a "service" that can inspect the http headers and then dynamically build and cache a new "service stack" to then pass the request down.

**Comment by LucioFranco** [comment]
@drusellers yup, this is what https://github.com/linkerd/linkerd2-proxy does. I believe they use a `MakeService<MyPerRequestConfig>` then build a new service stack from that then call it with the request. This then generates kinda like a tree of service stacks where the leaves are kinda dynamic if that makes sense. From this built service stack you could say store it somewhere and reuse it for subsequent requests.

**Comment by carllerche** [comment]
Linkerd is in the process of migrating to the new layer stuff (PR: https://github.com/linkerd/linkerd2-proxy/pull/235).

@drusellers What it sounds like you want is a router layer. Linkerd includes a custom one, but at some point we need to figure out how to bring it into here. The impl is [here](https://github.com/linkerd/linkerd2-proxy/blob/tower-layer/lib/router/src/lib.rs).

The main question is whether or not each service stack is the same type (the output of the same `MakeService`, just perhaps with different configuration settings), or is each route a completely different service type. The router implementation would depend on this.

**Comment by carllerche** [comment]
Is there an action item to take away at this point?

**Comment by davidbarsky** [comment]
@carllerche: The impression I got is that the draft you've got in https://github.com/tower-rs/tower/pull/251 is the way we're going.

**Comment by drusellers** [comment]
Thank you everyone. :) You gave me some item to chew on and that I'm not completely crazy. :)
