### ISSUE TITLE
util: add LayerFn which implements `Layer` for a closure

### ISSUE THREAD

**Issue by seanmonstar** [tower-rs/tower#267]
Many layers are *very* simple, and it'd be useful to have a way to create one from a closure.

### Example implementation

```rust
#[derive(Clone, Copy, Debug)]
pub struct LayerFn<F>(F);

impl<F, S, Out> Layer<S> for LayerFn<F>
where
    F: Fn(S) -> Out,
{
    type Service = Out;

    fn layer(&self, inner: S) -> Self::Service {
        (self.0)(inner)
    }
}
```

Need to decide on an exposed name:

- `tower::layer_fn()`
- `tower::layer::from_fn()` (similar to `std::iter::from_fn`)
- `tower::layer::mk()` (take from finagle, less clear)

**Comment by carllerche** [comment]
`layer_fn` to mirror `service_fn` 👍

**Comment by seanmonstar** [comment]
I'm kinda partial to following `std::iter::from_fn`...

**Comment by carllerche** [comment]
Should `service_fn` be renamed then?
