### ISSUE TITLE
Implement mapping combinators in tower

### ISSUE THREAD

**Issue by drusellers** [tower-rs/tower#272]
I would like to see tower implement a mapping combinator into the `ServiceBuilder` api. Something similar to what we say in PR #251 would be quite nice.

```rust
let mut service = ServiceBuilder::new()
            .map_request(|request: &'static str| request.to_string())
            .layer(FilterLayer::new(|_request: &String| Ok(())))
            .concurrency_limit(100)
            .buffer(5)
            .service(my_service);
```

I've been hacking on it locally, and it seems pretty easy to add in. I'm currently just fighting some generic type declarations. I'm currently playing with the idea of the mapping function being `Fn(Request) -> Future` (where I'm a little fuzzy on the exact return type).

**Comment by jonhoo** [comment]
There is what I believe to be a partial implementation of this in #396. @LucioFranco also mentioned in #243 that he has an implementation elsewhere that he can bring over. We should sort that out :p

**Comment by LucioFranco** [comment]
Done in #435
