### ISSUE TITLE
Proposal: Whenever Possible, Prefer Runtime-Agnostic Libraries

### ISSUE THREAD

**Issue by davidbarsky** [tower-rs/tower#296]
Proposal: As a general principle for future development, Tower's middleware should prefer to use runtime-agnostic libraries over Tokio-specific libraries. While Tokio might be the most mature Futures runtime, I don't think Tower should assume that is the _only_  runtime.

At the moment, Tower already has minimal dependencies on Tokio. Whenever Tower moves to `std::future::Future`, I think that that `tokio::timer` can be replaced by [futures-timer](https://github.com/rustasync/futures-timer), any performance concerns notwithstanding.

**Comment by seanmonstar** [comment]
I agree with the principle!

For timers, it'd be cool if there was a hook or generic way to allow different timer implementations. If one isn't running on a tokio runtime, the the timeout middleware won't work using tokio-timer. If on a tokio runtime, however, it seems unfortunate to have a separate timer wheel running when tokio already has one.

**Comment by carllerche** [comment]
What is the advantage of futures-timer over tokio-timer?

**Comment by seanmonstar** [comment]
The one thing I see is that futures-timer always works, tokio-timer requires the delays to be created while the TLS slot is set, so polling the delay in some other executor can result in a timer error. The downside to that "always works" is that futures-timer always spawns a thread to hold the timer, and thus always has synchronization cost.

**Comment by carllerche** [comment]
Tokio-timer has the ability to add a fallback. It used to do this but we decided to remove it specifically to avoid silent thread creation.

**Comment by hawkw** [comment]
> For timers, it'd be cool if there was a hook or generic way to allow different timer implementations.

A "timer facade" crate that abstracts over different timer impls seems like it might be a good idea, if it's something that implementations are willing to adopt?

**Comment by davidbarsky** [comment]
> A "timer facade" crate that abstracts over different timer impls seems like it might be a good idea, if it's something that implementations are willing to adopt?

I think a timer facade would be handy, assuming we find a sharable interface.

**Comment by jonhoo** [comment]
@davidbarsky it _might_ be easier to develop a facade on top of https://github.com/jonhoo/tokio-os-timer initially, as it is more aligned with the "standard" reactor-based notify/wakeup pattern.

**Comment by carllerche** [comment]
A facade would either have to be trait based (add generics to the tower APIs) or require boxed trait objs. It is unclear to me that the benefit outweighs the cost.

**Comment by davidbarsky** [comment]
What if it wasn’t strictly a facade, but most implementations had a similar-enough API so that timers could be swapped out on-the-fly using Cargo features?

Alternatively, I can see some utility of timers being in the futures crates.


________________________________
