### ISSUE TITLE
Expose subcrates default features in `tower`.

### ISSUE THREAD

**Issue by samscott89** [tower-rs/tower#306]
Tower pulls in tower-buffer  which has the `log` feature enabled by default. Would be good to re-expose this as a default feature in tower so it can be turned off if necessary. Presumably will be the same for other tower-* crates if/when tracing gets added to them.

**Comment by samscott89** [comment]
Perhaps better to solve this in tracing - https://github.com/tokio-rs/tracing/issues/204

**Comment by jonhoo** [comment]
This is fixed by #431, and specifically #432.
