### ISSUE TITLE
Recommended naming for tower crates

### ISSUE THREAD

**Issue by hlb8122** [tower-rs/tower#374]
I've whipped up a couple of generic services and middleware built for tower and popped them into a lib.

Is it OK to publish this under `tower-pop` or would you prefer that the `tower-` prefix is reserved specifically for foundational crates distributed directly from the core tower devs?

**Comment by LucioFranco** [comment]
Hey! Thank you for asking! <3

We don't mind at all, the name can be used for anything that is related to tower! We'd even like to create a list of all the things that work/use tower too!

**Comment by hlb8122** [comment]
Thanks, I really life the interface and the approach. I hope more projects build on this in the future.

**Comment by LucioFranco** [comment]
Great, I am almost done refreshing tower with tokio 0.2 and plenty more improvements in the next few months.
