### ISSUE TITLE
Service never attempts to reconnect

### ISSUE THREAD

**Issue by bmwill** [tower-rs/tower#383]
When running the helloworld client/server from [tonic](https://github.com/hyperium/tonic/tree/master/tonic-examples/src/helloworld) (with a modified client to run in a loop) I found that if a client ever has its connection broken to the server (due to me killing the server for some amount of time) that even if the server is brought back up and is healthy that the client is never able to reconnect and it appears this is due to the client never attempting to retry to establish a connection.

I would expect that the client should attempt to reestablish the connection if it ever has its connection with the server broken.

cc: @LucioFranco

**Comment by LucioFranco** [comment]
Closed via https://github.com/tower-rs/tower/pull/437
