### ISSUE TITLE
Migrate crates to use `Error: From<S::Error>`

### ISSUE THREAD

**Issue by LucioFranco** [tower-rs/tower#387]
Currently, we have a mix and match of crates that use `From` bounds over `Into` bounds. This is causing issues when wanting to compose the services together. I suggest we move them all to `From` since that is what `Try` is based on.

cc @jonhoo @seanmonstar @carllerche @hawkw

**Comment by seanmonstar** [comment]
`From` is much more convenient to use with `?`. The reason I used `Into` is because that's what `std::io::Error::new` uses. It's *technically* possible that things can implement `Into` and not `From` (though not the reverse), but it should be very few things?

**Comment by hawkw** [comment]
I think it _might_ be worth revisiting the decision to go with `Into` rather than `From` as part of #431. Not being able to automatically convert errors with `?` is a bit of a pain.

**Comment by LucioFranco** [comment]
I do find bounds that use from much harder to read than using into which feels very intuitive to me. If its at the cost of using ? I think its fine.

**Comment by jonhoo** [comment]
I'd like to get a better sense of the trade-off space here. If we use `Into`, where is it possible/not possible to use `?`. If we use `From`, where is it possible/not possible to use `?`. What do other libraries do?

**Comment by jonhoo** [comment]
I also just noticed today that the Rust documentation recommends using `Into` in bounds: https://doc.rust-lang.org/std/convert/trait.From.html. I feel like there's something missing in the story here. In some sense, it feels like it's wrong for `?` to rely on `From` :/

**Comment by jonhoo** [comment]
See also my comment here: https://github.com/rust-lang/rust/issues/31436#issuecomment-619427209

**Comment by hawkw** [comment]
I believe we've decided all error bounds should be `Into`.
