### ISSUE TITLE
poll_ready, ctx and futures

### ISSUE THREAD

**Issue by MOZGIII** [tower-rs/tower#392]
`poll_ready` at `Service` takes `cx: &mut Context<'_>` now. It looks like this it's, therefore, possible to *wait* for the service to become ready. So... Is this intended?
If it's a mistake and `ctx` should be removed - no further questions. :smile: 
If it's not - why isn't there a `fn ready(&mut self) -> ReadyFuture<Self> { ... }`? `ReadyFuture` here would a `tower`'s `struct` that just polls on ready. Just for convenience.

Currently what I have to do is this:
```rust
futures::future::poll_fn(|ctx| service.poll_ready(ctx)).await?;
```

Maybe I'm not understanding the whole idea here, of so, could someone explain, please?

**Comment by walfie** [comment]
it does exist in tower_util:
https://docs.rs/tower-util/0.3.0-alpha.1/tower_util/struct.Ready.html

and also as part of `ServiceExt` (although it looks like this one isn't released yet)
https://github.com/tower-rs/tower/blob/2dc9a72bea615dcbf855bdfcaf3083458d9f15a6/tower-util/src/lib.rs#L50-L56

**Comment by MOZGIII** [comment]
Oh, ok. It's not easy to discover. Thanks!
