### ISSUE TITLE
Publish `balance` and friends

### ISSUE THREAD

**Issue by LucioFranco** [tower-rs/tower#395]
Currently, we have an alpha release of tower and its sub crates. We never had a `0.1` release. So I woudl like to bring up we consider releasing it as a 0.3 and move forward. I think as long as we keep `tower-service` as `0.3` it should be fine to release.

@jonhoo and @olix0r I'd like to know if you both have any reservations about going ahead and publishing those as a `0.3`?

**Comment by jonhoo** [comment]
I think publishing as `0.3` is fine. I recall @olix0r wanting to do something about the `pool` module following #303, but forget the exact details.

**Comment by LucioFranco** [comment]
cool, I think if we want to move pool stuff around we can do that in a 0.4, I am gonna try to get these all published today.

**Comment by jonhoo** [comment]
This is done.
