### ISSUE TITLE
Call `ServiceExt::<T>::ready`

### ISSUE THREAD

**Issue by zyctree** [tower-rs/tower#406]
sometimes i need to write like 

```rust
ServiceExt::<&str>::ready(&mut s).await?;

// following is the Service implement for Trait
impl<Req> Service<Req> for S
where Req: SomeTrait
{ ... }
```

and at most times, all the `poll_ready` are implemented the same,
so all I need is something like

```rust
s.ready().await?
// or with another method name
s.any_ready().await?
```

**Comment by LucioFranco** [comment]
@zyctree hi! can you explain more what you are looking for? If the `&mut s` implements `Service` then you just need `ServiceExt` to be imported and call `ready`?

**Comment by zyctree** [comment]
when only one `Service<Req>` is implemented for `S`, it is ok to call `ready`

but when `Service<Req1>` and `Service<Req1>` are both implemented, `ready` need to known the type

here is the error message

```
error[E0698]: type inside `async` block must be known in this context
  --> tower-make/examples/tokio_tcp.rs:41:7
   |
41 |     s.ready().await?;
   |       ^^^^^ cannot infer type for type parameter `Request`
   |
```

**Comment by LucioFranco** [comment]
@zyctree sounds like you need to actually `call(Req)` which will allow the compiler to infer that what the generic for the Service trait is or youll have to annotate like you did.
