### ISSUE TITLE
tower::limit::RateLimit and series of query

### ISSUE THREAD

**Issue by IamFake** [tower-rs/tower#454]
When i'm wrapping my object with RateLimit object and with 1 times per 1 second limit, and then call it 6 times - i've got 6 calls to poll_ready func and only 2 calls to "call" func.

It's happen becouse in poll_ready we have following code

`
State::Limited(ref mut sleep) => {
        ready!(Pin::new(sleep).poll(cx));
}
`

and in this case "sleep" knows only context of the "last" query called for poll_ready, so 4 other queries won't be woked up (as i suppose).

**Comment by seanmonstar** [comment]
This is expected behavior. What are you doing with the requests that are "over limit"? Rejecting them immediately, or just collecting them to pass on once allowed?

If the latter, you can combine with `tower-buffer` to do exactly that.

**Comment by IamFake** [comment]
Hm, that's not obvious. I want them to pass on once allowed. Ok, thanks, I will try tower-buffer to solve that.

**Comment by seanmonstar** [comment]
As part of #431, we should improve the docs of that.
