### ISSUE TITLE
tower.rs website is void

### ISSUE THREAD

**Issue by yoshuawuyts** [tower-rs/tower#46]
Heya, I was looking [at the docs](https://tower-rs.github.io/tower/tower/), and at the top it points to https://tower.rs/ for more information.

The site itself does self-signed HTTPS it seems, and the unsafe http version doesn't seem particularly related to this project.

I'm not sure what the status of the domain is, but perhaps it might be useful to remove the reference to the site until a change has been made?

Thanks for your time; excited for how the project is shaping up! ✨

**Comment by bjorn3** [comment]
The certificate seems to be owned by https://orion.rs/ which when visited has a certificate owned by https://oriontelekom.rs/

**Comment by carllerche** [comment]
Thanks! There is no website yet :(
