### ISSUE TITLE
Add generic parameters to specify the error type of middleware that return their own error types

### ISSUE THREAD

**Issue by yaahc** [tower-rs/tower#461]
Right now tower provides ~5 service wrappers that introduce their own error variants in addition to the the errors returned by a wrapped service, e.g. `Buffer`. Currently they're setup so that each of these structs return a `Box<dyn Error>` which it can use to either return the inner error type or its own error type. This is ideal for convenient propagation of error types and API stability but has significant downsides when it comes to composition with other error handling types because `Box<dyn Error>` does not implement `std::error::Error` and `Box<dyn Error>` can only store types that implement `std::error::Error`.

Together these two restrictions make the given tower middleware incompatible with more feature rich error reporting types like `anyhow::Error` or `eyre::Report`. Because these reporting types implement `From<E: Error>` they can not implement `From<Box<dyn Error>>` or `Error`, because both implementations would violate the overlap rule. This means you cannot use error reporting types in services that are wrapped by tower middleware or convert the errors returned from the middleware into said error reporting types without significant amounts of boilerplate.

Instead of `Box<dyn Error>` these types should have a generic parameter added to them to specify the error type that will be used to unify the errors from the middleware and the inner service. This generic parameter could then be set to `Box<dyn Error>` which would opt into the current behaviour, it could be set to another error reporting type like `eyre::Report` letting the inner services construct more meaningful error reports and capture more context such as SpanTraces from within the inner service, or it could even be set to an enum type for users who wish to force explicit handling of all possible error variants.

This design has already been applied to `tower-batch` in `zebra` which is itself based on `tower-buffer`. Please refer to https://github.com/ZcashFoundation/zebra/pull/500 to see what changes were necessary. The key difference is that the new generic error type requires `crate::BatchError: Into<E>` and `S::Error: Into<E>`, instead of requiring `Into<Box>`.

cc @jonhoo @hawkw @LucioFranco

**Comment by LucioFranco** [comment]
cc @seanmonstar @carllerche

**Comment by yaahc** [comment]
Oh so update on this, I tried making the proposed changes to `tower-buffer` but its constraint that the error be clone able ended up interfering with my ability to use `eyre::Report` just as much as the `Box` does. So while this change would probably work for most of the error introducing layers in tower the one I really need it for still has issues. If I can think of a way to work around the clone issue I'll revisit this but for now I'm shelving this and just relying on `TracedError` to get spantraces through trait objects.

**Comment by hawkw** [comment]
@yaahc based on your comment from July my read is that this is unfortunately probably not going to work. Do you think this issue should be closed, or is there anything else worth exploring in this area that might mean we should keep it open?

**Comment by yaahc** [comment]
I think we can go ahead and close this

**Comment by hawkw** [comment]
Thanks, just wanted to make sure.

**Comment by yokomizor** [comment]
Would it be possible to expose `T::Error` using enums? Something like:

```
enum BufferError<T> {
    ServiceError(T),
    WorkerError(crate::BoxError),
}

...

impl<T, Request> Service<Request> for Buffer<T, Request>
where
    T: Service<Request>,
{
    type Error = BufferError<T::Error>;
```

Otherwise, is there any other way to handler T::Error?

**Comment by yokomizor** [comment]
Ok, I have just found #131.

**Comment by davidpdrsn** [comment]
@yokomizor It's possible to downcast to the concrete error type.

**Comment by yokomizor** [comment]
Oh, I see. I was not aware of Box::downcast existence. Huge thanks @davidpdrsn!
