### ISSUE TITLE
A multi-layered *readability* issue with naming in "tower-layer" and "tower/tower/builder"

### ISSUE THREAD

**Issue by zancas** [tower-rs/tower#464]
There are too many things named "layer" in the code.

@AloeareV and I started with the intention of understanding what a `ServiceBuilder` does.

From the docs we learned that `requests` are processed in the same order as the `ServiceBuilder` layer-addition methods (`buffer`, `concurrency_limit`, etc..) are called.

Layers process their requests in the opposite (inner to outer) order, of the order by which they were added to the stack.

After some poking we determined that [Layer](https://github.com/tower-rs/tower/blob/ab7518ef1360fc6a0624d30364c315a51c569ca2/tower-layer/src/lib.rs#L84) and [ServiceBuilder](https://github.com/tower-rs/tower/blob/ab7518ef1360fc6a0624d30364c315a51c569ca2/tower/src/builder/mod.rs#L104) have multiple elements named "layer".

As far as I can tell this only effects readability, but for me the effect was significant.  When I was studying the code I reached a point where the word "layer" had been encountered so many times with so many different meanings that my brain dropped to character-level parsing of the word.

"l"-"a"-"y"-"e"-"r"...  this didn't help.

Updating the names would be a breaking change, so it might not be worth it, but documenting the meanings here might help others understand the code..   and perhaps the documentation can move into the source.  At the very least writing down this summary is helpful to me!   So the following lists the "layer"s and their meanings, along with some potential new-names that might make things more readable.

###  [the field "layer"](https://github.com/tower-rs/tower/blob/ab7518ef1360fc6a0624d30364c315a51c569ca2/tower/src/builder/mod.rs#L106)

In (what I understand to be) the default flow this is either an [Identity](https://github.com/tower-rs/tower/blob/ab7518ef1360fc6a0624d30364c315a51c569ca2/tower-layer/src/identity.rs#L9) (a noop layer that returns the `Service` it is passed) or a `Stack` (a Layer that contains a LIFO sequence of Layers).

Perhaps this field could be renamed "layers".

### [the method "layer"](https://github.com/tower-rs/tower/blob/ab7518ef1360fc6a0624d30364c315a51c569ca2/tower/src/builder/mod.rs#L120)

Perhaps this could be renamed "add_layer" and the generic type parameters `L` and `T` could be renamed `Outer` and `Inner` to match their definitiions in [Stack](https://github.com/tower-rs/tower/blob/ab7518ef1360fc6a0624d30364c315a51c569ca2/tower-layer/src/stack.rs#L6)

### [the method "layer"](https://github.com/tower-rs/tower/blob/ab7518ef1360fc6a0624d30364c315a51c569ca2/tower-layer/src/lib.rs#L89)

This is a method of a Trait named `Layer` it takes a `Service` as a parameter, in that context we think `apply_to` would be an unambiguous improvement in readability.

Finally:

### The Implementation of [`Layer::apply_to`](https://github.com/tower-rs/tower/blob/ab7518ef1360fc6a0624d30364c315a51c569ca2/tower-layer/src/stack.rs#L25) for `Stack`

 There's a local variable `inner`.   This could be changed to `service_with_inner_applied`, which is verbose-but-explicit and only used in two places.

  Going the other way, perhaps the local variable could be discarded altogether:

`self.outer.apply_to(self.inner.apply_to(service))`

**Comment by LucioFranco** [comment]
Thanks for these suggestions! I think in general we just need more docs which is something we are working on. We have a spring cleaning issue with some action items but I think that is our next step is to actually clarify what these terms mean.

In general we consider a tower layer to be some type middleware that takes another service and wraps it to provide some sort of benefit. The stack is composed of these layers where the leaf is some sort of transport. Hopefully, that makes some sense :D

**Comment by zancas** [comment]
Oh!   This is a very interesting statement:   "The stack is composed of these layers where the leaf is some sort of transport."
It might help extend my mental model.

I will go looking for the Spring Cleaning Issue.

**Comment by LucioFranco** [comment]
Thanks for this feedback, going to close this issue, if you want to continue to discuss feel free to open it :)
