### ISSUE TITLE
The use of `Box<dyn Error>` in layers has usability issues

### ISSUE THREAD

**Issue by bruceg** [tower-rs/tower#465]
Several layers, notably `struct Timeout` in our use case, have `BoxError` as their error type. This causes difficulty in outer layers that try to dispatch based on this error type. Since is a boxed type, code can't directly use the contained error other than through `trait Error`. While it is possible to match based on `error.downcast_ref::<T>()`, it is impossible to do so exhaustively. That is, it is impossible to guarantee that all possible types `T` are covered.

This could be avoided with a generic error enum for such layers. One variant would be the error type of the inner layer, along with any other variants required for the layer errors (just `Elapsed` for the `Timeout` layer). This would allow outer layers to simply match on the enum and the compiler could guarantee exhaustiveness.

I recognize this is a breaking API change for any such outer layer. If you think it is worth doing, I can provide an implementation for at least the `Timeout` layer that could serve as the basis for the other such layers.

**Comment by seanmonstar** [comment]
We used to have an enum for each middleware, exactly as you describe. However, that has a lot of annoying problems as well, which are described in this issue: https://github.com/tower-rs/tower/issues/131

**Comment by bruceg** [comment]
I see. Since you've been there before, no point pursuing this further.
