### ISSUE TITLE
0.3.2 release with service combinators

### ISSUE THREAD

**Issue by hdevalence** [tower-rs/tower#468]
Would it be a great deal of work to backport the changes from #396 to the v0.3.x branch and release them in an 0.3.2 release? They'd be very useful for us, but if it's a lot of work it's totally understandable if it would be better to wait for a future 0.4 release.

**Comment by LucioFranco** [comment]
@hdevalence do you still want this or can we just ship 0.4 with it?

**Comment by hawkw** [comment]
Now that 0.4 is out, I think this isn't really relevant any longer...
