### ISSUE TITLE
hedge middleware has fixed size for timing histogram

### ISSUE THREAD

**Issue by hdevalence** [tower-rs/tower#475]
The `Hedge` middleware uses [`hdrhistogram::Histogram::new_with_bounds`](https://docs.rs/hdrhistogram/7.1.0/hdrhistogram/struct.Histogram.html#method.new_with_bounds) with hardcoded values `1` (min, ms), `10_000` (max, ms), and `3` (significant figures). 

When using the `Hedge` middleware in front of a service that takes longer than 10 seconds to process a request, the middleware displays a big error message that it failed to update the histogram.

There seem to be a few potential ways this problem could be solved:

1.  Removing the error message and failing silently;
2.  Allowing user-specified bounds on the histogram (increases API complexity);
3.  Allow automatic resizing of the histogram (either by setting no bound, or by using [`Histogram::auto`](https://docs.rs/hdrhistogram/7.1.0/hdrhistogram/struct.Histogram.html#method.auto)).

It seems like (3) is the best in terms of correctness, and it would be a drop-in change.  The only downside is that resizing the histogram might cause a latency spike. (2) doesn't have this problem, but does make the API more complicated.

**Comment by teor2345** [comment]
Another possible solution:
4. Clamp the values at the 10s mark

Not a great option, but at least it's quick.

**Comment by hdevalence** [comment]
Maybe the cleanest thing to do from a maintainability standpoint would be to enable auto-resizing (3). If someone has latency issues in the future another API could always be added then.

**Comment by hawkw** [comment]
> Maybe the cleanest thing to do from a maintainability standpoint would be to enable auto-resizing (3). If someone has latency issues in the future another API could always be added then.

That seems like the right approach to me.

**Comment by hawkw** [comment]
Fixed by #484.
