### ISSUE TITLE
A compose/pipeline util combinator

### ISSUE THREAD

**Issue by davidpdrsn** [tower-rs/tower#517]
I’ve have gotten an idea for a combinator we don’t currently have afaik.

Basically it’s function composition but for services. So composing two services gives one service where the output of the first service becomes the input to the second  service.

Truth be told I don’t have a use case for this combinator but still think it’s interesting. Is this something you think would be interested in?

**Comment by olix0r** [comment]
My opinion is that it's best to avoid adding utilities just for the sake of adding them -- it's more code that needs to be maintained/updated etc. It's fairly trivial to implement new services when they're needed and, unless these utilities are being reimplemented many times over, it's probably not worth the cost of promoting them to the core library.

Also, this should already be pretty easy to accomplish by mixing AndThen and Oneshot.

**Comment by davidpdrsn** [comment]
Fair enough. Was just a thought 😊
