### ISSUE TITLE
[question]: tower and pub/sub

### ISSUE THREAD

**Issue by derekdreery** [tower-rs/tower#534]
I want to make an app, and tower is a really good fit for me, except for the fact that there are times a notification should be sent to clients outside of the `request -> response -> request ...` loop. I was wondering if anyone had ideas how best to do this, either inside or outside of `tower`, and if it were something that `tower` might support in the future?

One way it could be implemented is adding a byte at the beginning of frames distinguishing between responses and notifications, but there might be more performant ways depending on the application. At each end it involves having state and writing a function `msg -> state -> state` where `msg` could be the response or a notification, such that the app is always consistent. I don't know how to provide an API for the ergonomically.

Currently I roll my own protocol and framing on top of raw tokio tcp streams, but I feel like it is a common pattern and would benefit from pooling resources for a base abstraction.

**Comment by olix0r** [comment]
I'm not sure that any new abstractions are needed. At least, I wouldn't start by trying to identify the abstraction. Implement it at least once before generalizing ;)

For example, in a pub/sub model, we might model a client as a `Service<Topic, Response = Events>` where `Events` is a `futures::Stream<Item = Event>`. It would be pretty straightforward to then model an event handling pipeline as a `Service<Event, Response = ()>`. I could envision tower including an adapter for such a `Service` to implement `futures::Sink<Event>` so it can easily be attached to streams... My point is: the abstractions we already have are probably enough to get you 95% of the way when building a pub/sub system.

So, in my opinion, Tower is really just `Service` and a set of utility general implementations. If there are entirely new traits that need to be devised---and I'm not sure that there are---then they probably belong outside of Tower. However, if you find that, in building a pub/sub system, you end up implementing very general service implementations, they may be a good candidate to be included in Tower.

**Comment by derekdreery** [comment]
I need to think about this before I respond properly.
