### ISSUE TITLE
Switch from pin-project to pin-project-lite

### ISSUE THREAD

**Issue by seanmonstar** [tower-rs/tower#594]
I doubt we actually need the extra features of the former, and changing to to "lite" will be a compilation speed improvement.

**Comment by hawkw** [comment]
Looks like `tower::buffer` currently uses `PinnedDrop`: https://github.com/tower-rs/tower/blob/e1760d385d06c2f55dbd0b0b8054f176cff8c505/tower/src/buffer/worker.rs#L23-L24 which `pin-project-lite` doesn't support. 

I think it may be possible to refactor the implementation somewhat so that the drop impl is not needed. We could probably add a wrapper struct around just the semaphore with a `Drop` impl, instead.

**Comment by Michael-J-Ward** [comment]
Started the grind-work [part of this migration](https://github.com/Michael-J-Ward/tower/tree/migrate-to-pin-project-lite).

Two limitations of `pin-project-lite` that I ran into:

1) [does not support tuple structs / variants - which is labelled as won't fix.](https://github.com/taiki-e/pin-project-lite/blob/416be96f7777862c68b567c92a91887f69a8c2b3/src/lib.rs#L401-L408)
2) [Cannot interoperate with other field attributes](https://github.com/taiki-e/pin-project-lite/issues/3) including doc comments

This means each `StateEnum` needs a small refactor [like this one](https://github.com/Michael-J-Ward/tower/commit/dc42c2567d515a111f8d6699ebaecbcb49e48624).

**Comment by taiki-e** [comment]
> which `pin-project-lite` doesn't support.

No. I recently added support for it: https://github.com/taiki-e/pin-project-lite/releases/tag/v0.2.7

**Comment by Michael-J-Ward** [comment]
And [implemented for buffer::Worker](https://github.com/tower-rs/tower/pull/595/commits/ade48a255311b124163f32cf8242e0fba70fc12a)

@taiki-e is there anything preventing trait bounds on the `PinnedDrop` impl

**Comment by taiki-e** [comment]
https://github.com/tower-rs/tower/pull/595/commits/ade48a255311b124163f32cf8242e0fba70fc12a

> However, it does not support generic trait bounds on the PinnedDrop impl.
>
> To workaround this, I removed the T::Error bound from the Worker struct definition,
> and moved `close_semaphore` to a a new impl without that trait bound.

Hmm, that's odd... I'll take a look later.
