### ISSUE TITLE
`cargo deny check bans` hangs when run in the tower repo

### ISSUE THREAD

**Issue by davidpdrsn** [tower-rs/tower#619]
When merging https://github.com/tower-rs/tower/pull/616 I ran into CI getting stuck on the `cargo-deny` step. Turns out `cargo deny check bans` hangs when run in the tower repo, also locally. The other checks work fine.

I disabled the step in https://github.com/tower-rs/tower/pull/616/commits/03066ddbbd369818d2a3ef438ec64a6e3ea0d987 to be able to merge.

@Jake-Shadle do you have any idea what might cause this?

**Comment by Jake-Shadle** [comment]
Must be a bug somewhere that leads to recursion, surprised no one has seen it before, I'll take a look tomorrow, filed https://github.com/EmbarkStudios/cargo-deny/issues/375

**Comment by davidpdrsn** [comment]
Thank you!

**Comment by repi** [comment]
Believe this is fixed now from the PR fix @Jake-Shadle did:
- https://github.com/EmbarkStudios/cargo-deny/pull/395

**Comment by Jake-Shadle** [comment]
Oops yes, forgot to update the action, will do that and file a pr to close this.
