### ISSUE TITLE
Service as a struct member

### ISSUE THREAD

**Issue by PFAhard** [tower-rs/tower#634]
How can I use a service as a struct member to provide a higher level API?

Whatever i do, I get mismatched types, like this: found struct `tower::limit::RateLimit<tower::util::ServiceFn<[closure@src/main.rs:28:36: 28:66]>>`

How can i bypass closure type?

**Comment by olix0r** [comment]
@PFAhard you can either make your struct generic over the service type or use [`BoxService`](https://docs.rs/tower/latest/tower/util/struct.BoxService.html) (or [`BoxCloneService`](https://docs.rs/tower/latest/tower/util/struct.BoxCloneService.html)).

**Comment by PFAhard** [comment]
@olix0r It doesn't change anything: every closure has a distinct type and so could not always match the caller-chosen type of parameter `T`

**Comment by olix0r** [comment]
@PFAhard I'm not sure what you mean. You can find plenty of examples of using generic service types in this crate, though. For instance the `Timeout` holds a generic inner service https://github.com/tower-rs/tower/blob/2f50b49f5af54dced258b2d781894848cc79fdfb/tower/src/timeout/mod.rs#L17-L22

It might be easier to discus a concrete code example.

**Comment by PFAhard** [comment]
if i use generic, the problem is just passed one level up
![image](https://user-images.githubusercontent.com/50257230/152306700-23b6875e-fe97-48d0-a3bb-5e7468c5dbaf.png)

**Comment by PFAhard** [comment]
![image](https://user-images.githubusercontent.com/50257230/152308773-979b3344-827e-403c-a850-a61732e55e8e.png)

**Comment by olix0r** [comment]
As in the `timeout` example, you'll need to use type constraints to enforce that `T` is actually a `Service`. I wouldn't use `svc: RateLimit<ServiceFn<T>>`, I would use `svc: T` and then `where T: Service<Request, Response = Response>` ...

or, as I mentioned above, you can box the service so its type is opaque

**Comment by PFAhard** [comment]
I've already tried both of your options before, both don't work.
But everything is ok, I solved everything with the help of https://crates.io/crates/governor works much better and easier.
