### ISSUE TITLE
more exemple for the version 0.4 and tower 0.14

### ISSUE THREAD

**Issue by templine** [tower-rs/tower#664]
hard time trying to use tower no exemples, and the existed one are outdated

**Comment by davidpdrsn** [comment]
Please be more specific.

Which examples specifically are outdated?

Tower 0.14 doesn't exist, which crate do you mean?

**Comment by LucioFranco** [comment]
We should probably add more examples anyways, but closing this in favor of #675

**Comment by zhaopinglu** [comment]
Love to see more examples.
