### ISSUE TITLE
Docs for `BoxService` point at module level documentation which is missing

### ISSUE THREAD

**Issue by dcormier** [tower-rs/tower#683]
The [docs for `tower::util::BoxService`](https://docs.rs/tower/0.4.13/tower/util/struct.BoxService.html) state, in part, "See module level documentation for more details." But there is [no additional documentation of `BoxService` in that module](https://docs.rs/tower/0.4.13/tower/util/index.html).

Digging a little, I can see that this probably meant [the documentation in `tower::util::boxed`](https://github.com/tower-rs/tower/blob/tower-0.4.13/tower/src/util/boxed/mod.rs#L1-L33), but that module is not public.

**Comment by davidpdrsn** [comment]
Oh good find! I say we just make the `tower::util::boxed` module public. Are you up for submitting a PR for that?

**Comment by dcormier** [comment]
Sure, I can do that.

**Comment by LucioFranco** [comment]
@dcormier maybe instead of module level can we inline those docs to `BoxService`? So instead of making the module public we just add those docs to the struct and remove references to module level docs.

**Comment by seanmonstar** [comment]
I was going to suggest the same as Lucio.

**Comment by dcormier** [comment]
Alright. Those docs have been moved.
