### ISSUE TITLE
`BoxService` is unnecessarily `!Sync`

### ISSUE THREAD

**Issue by SabrinaJewson** [tower-rs/tower#697]
This type doesn’t have any methods accessing the inner value with `&self`, so by [`SyncWrapper`](https://docs.rs/sync_wrapper/latest/sync_wrapper/struct.SyncWrapper.html) logic it can be unconditionally `Sync` — however currently, it never implements the trait.

Options to fix this include:
* Add an extra dependency on `sync_wrapper`;
* Add `unsafe` code to `tower`;
* Wait for `SyncWrapper` to be added to `std`.

Opinions on which would be (un)desirable?

Edit: Realized that this doesn’t apply to `BoxCloneService`, since that type needs `Clone` and so obviously must be `!Sync`.

**Comment by LucioFranco** [comment]
Yeah, we can revisit this, though I think for now the current work around is to import `SyncService` yourself and use that to get the `Sync` impl.
