### ISSUE TITLE
Adding Service Wrapper that allows to share services for compatibility with Axum route layers

### ISSUE THREAD

**Issue by teamwork-alockhart** [tower-rs/tower#712]
**Overview**

Allow services that don't implement clone to be clone-able through an Arc, mainly for Axum router compatibility.

**Motivation**

As you may be aware, Axum is currently designed with Tower-compatibilty in mind. As a result this could be considered more of an Axum issue. However, creating a solution using Tower terminology was easier, so I'm just suggesting it just in case it's useful.
When creating layers in Atom, it is required that the inner service produced by the layer implements `Clone`.
The original problem that motivated me to open this issue is that `RateLimit` does not currently implement `Clone`, therefore making it very difficult to use with Axum's current interface. 

Here is a naive attempt at rate limiting using Axum:
```rust
use axum::Router;
use tower::limit::RateLimitLayer

Router::new()
        .route("/", get(example))
        .route_layer(RateLimitLayer::new(200, Duration::from_secs(1)))
```

However, compilation fails with this error:

```
the trait bound `tower::limit::RateLimit<axum::routing::Route<_>>: std::clone::Clone` is not satisfied
the trait `std::clone::Clone` is not implemented for `tower::limit::RateLimit<axum::routing::Route<_>>`
```

**Proposal**

`RateLimit` on it's own not being clone makes sense to me. However, I got the feeling that Arc could be used as a nice compromise to create a wrapping layer that _does_ allow the Service to be `Clone`d in a useful way.
Here is my own implementation.
Notes: 
- I'm not a professional developer, so I may be overlooking something critical.
- I originally wanted to derive Clone, but apparently the provided implementation is not generic over all inputs I wanted, so I manually implemented it.
- One unfortunate part of my current solution is using inner-mutability. I'd normally try to avoid this, but I haven't been able to figure out an alternate solution at this point.

```rust
use tower::{Layer, Service};
use std::sync::Arc;
use tokio::sync::Mutex; // Maybe this implementation should use std instead

#[derive(Debug)]
pub struct ArcLayer<Request, S: Service<Request>, T: Layer<S>> {
    inner: T,
    _marker: PhantomData<ArcService<Request, S>>,
}

impl<Request, S: Service<Request>, T: Layer<S>> ArcLayer<Request, S, T> {
    pub fn new(layer: T) -> Self {
        Self {
            inner: layer,
            _marker: PhantomData,
        }
    }
}

impl<Request, S: Service<Request>, T: Layer<S>> Layer<S> for ArcLayer<Request, S, T>
where
    <T as Layer<S>>::Service: Service<Request>,
{
    type Service = ArcService<Request, <T as Layer<S>>::Service>;

    fn layer(&self, inner: S) -> Self::Service {
        let service = self.inner.layer(inner);
        ArcService::new(service)
    }
}

#[derive(Debug)]
pub struct ArcService<Request, S: Service<Request>> {
    inner: Arc<Mutex<S>>,
    _marker: PhantomData<Request>,
}

impl<Request, S: Service<Request>> ArcService<Request, S> {
    pub fn new(service: S) -> Self {
        Self {
            inner: Arc::new(Mutex::new(service)),
            _marker: PhantomData,
        }
    }
}

impl<Request, S: Service<Request>> Clone for ArcService<Request, S> {
    fn clone(&self) -> Self {
        Self {
            inner: self.inner.clone(),
            _marker: PhantomData,
        }
    }
}

impl<Request, S: Service<Request>> Service<Request> for ArcService<Request, S> {
    type Response = <S as Service<Request>>::Response;
    type Error = <S as Service<Request>>::Error;
    type Future = <S as Service<Request>>::Future;

    fn poll_ready(
        &mut self,
        cx: &mut std::task::Context<'_>,
    ) -> std::task::Poll<Result<(), Self::Error>> {
        let mut lock = loop {
            if let Ok(lock) = self.inner.as_ref().try_lock() {
                break lock;
            }
        };
        lock.poll_ready(cx)
    }

    fn call(&mut self, req: Request) -> Self::Future {
        let mut lock = loop {
            if let Ok(lock) = self.inner.as_ref().try_lock() {
                break lock;
            }
        };
        lock.call(req)
    }
}

``` 

After the change, you can use rate limiting with Axum in the following way.

```rust
Router::new()
        .route("/", get(example))
        .route_layer(ArcLayer::new(RateLimitLayer::new(
            200,
            Duration::from_secs(1),
        )))
```
What do you think? Would this be useful as a wrapper for services that shouldn't implement `Clone`, but be shared instead?

**Comment by davidpdrsn** [comment]
That is pretty much what [`Buffer`](https://docs.rs/tower/latest/tower/buffer/index.html) does.

Specifically in terms of rate limiting I don't think tower's option is a good fit for http servers because
1. It isn't Clone like you mention
2. It changes the error type, whereas axum requires `Infallible` so you always send a response. Instead you have to do that mapping manually using axum's error handling stuff
3. It does't provide any feedback to the client through response headers.

I think a more HTTP specific rate limiting could be added to tower-http.

**Comment by teamwork-alockhart** [comment]
@davidpdrsn 
Thank you for the quick response.
I see your point here - it's not very ergonomic when considering with Axum's normal API.
I saw [this previous issue](https://github.com/tokio-rs/axum/discussions/877) opened in Axum in which you answered that BufferLayer could be used as a workaround, but I wasn't able to figure that out unfortunately.
To be honest, I'm a little bit out of my depth, but if there is something I can do to contribute to legitimate solution, I would like to help.

**Comment by davidpdrsn** [comment]
You can do this:

```rust
use axum::{
    error_handling::HandleErrorLayer,
    http::StatusCode,
    response::{IntoResponse, Response},
    routing::get,
    BoxError, Router,
};
use std::time::Duration;
use tower::{buffer::BufferLayer, limit::RateLimitLayer, ServiceBuilder};

#[tokio::main]
async fn main() {
    let app = Router::new().route("/", get(|| async {})).layer(
        ServiceBuilder::new()
            .layer(HandleErrorLayer::new(handle_middleware_error))
            .layer(BufferLayer::new(1024))
            .layer(RateLimitLayer::new(10, Duration::from_secs(1))),
    );

    axum::Server::bind(&"0.0.0.0:3000".parse().unwrap())
        .serve(app.into_make_service())
        .await
        .unwrap();
}

async fn handle_middleware_error(err: BoxError) -> Response {
    StatusCode::INTERNAL_SERVER_ERROR.into_response()
}
```

Also I was wrong about tower's rate limit changing the error type. It just relies on `poll_ready`.

**Comment by teamwork-alockhart** [comment]
Thanks for showing me how to do this! I'll have to read a bit more on how this works, but I think I understand.
I guess I'll close for now - it seems like this is an easy enough workaround that a solution like the one you mentioned above wouldn't be in high demand.
