### ISSUE TITLE
Can I ask one question?

### ISSUE THREAD

**Issue by Kotodian** [tower-rs/tower#714]
Hi, I'm a rust newer.When I read the steer's source code, I found the PhantomData in Steer, I'm really confused about it. Therefore, I just want to know the case that why we need the PhantomData.

**Comment by LegNeato** [comment]
Hello! Welcome to Rust.

Have you checked out https://doc.rust-lang.org/std/marker/struct.PhantomData.html?

`Steer` is generic (that is, it doesn't care about _what specific type_ of each is passed in) over three things--the services to steer to (`S`), the picker function to pick which service to steer to (`F`), and the request to pass through to the service (`Req`).

To perform the act of steering, `Steer` needs to store and use the the services to steer to (`S`) and the picker function to pick which service to steer to (`F`). So those are stored in the struct normally. But the logic in `Steer` _doesn't care_ about what the request (`Req`) is...it just blindly passes it to the picked service. But in Rust, you can't specify a generic without "using" it, as it may be a sign the programmer made a mistake. But `Steer` needs _both_ to allow any request _and_ as just mentioned it doesn't need to store or use it. So we are at a stalemate...`Steer` needs to behave one way and the compiler expects something else. `PhantomData` is a way to mark the generic request (`Req`) as stored and used _without actually storing or using it_. It is essentially telling the compiler, "I know this generic data is unused by `Steer`, this is ok and not a mistake."

**Comment by Kotodian** [comment]
I'm really appreciate for your reply. I didn't describe my question correctly.From your rely, I understand the #PhantomData's  in #Steer.

But I want to know what is the difference between using #PhantomData in #Steer and not using #PhantomData.The code is as follows
```rust
use std::{
    collections::VecDeque,
    fmt,
    marker::PhantomData,
    task::{Context, Poll},
};

use tower_service::Service;

pub trait Picker<S, Req> {
    fn pick(&mut self, r: &Req, services: &[S]) -> usize;
}

impl<S, F, Req> Picker<S, Req> for F
where
    F: Fn(&Req, &[S]) -> usize,
{
    fn pick(&mut self, r: &Req, services: &[S]) -> usize {
        self(r, services)
    }
}

pub struct Steer<S, F> {
    router: F,
    services: Vec<S>,
    not_ready: VecDeque<usize>,
    // _phantom: PhantomData<Req>,
}

impl<S, F> Steer<S, F> {
    pub fn new(services: impl IntoIterator<Item = S>, router: F) -> Self {
        let services: Vec<_> = services.into_iter().collect();
        let not_ready: VecDeque<_> = services.iter().enumerate().map(|(i, _)| i).collect();
        Self {
            router,
            services,
            not_ready,
        }
    }
}

impl<S, Req, F> Service<Req> for Steer<S, F>
where
    S: Service<Req>,
    F: Picker<S, Req>,
{
    type Response = S::Response;

    type Error = S::Error;

    type Future = S::Future;

    fn poll_ready(&mut self, cx: &mut Context<'_>) -> Poll<Result<(), Self::Error>> {
        loop {
            if self.not_ready.is_empty() {
                return Poll::Ready(Ok(()));
            } else {
                if self.services[self.not_ready[0]]
                    .poll_ready(cx)?
                    .is_pending()
                {
                    return Poll::Pending;
                }

                self.not_ready.pop_front();
            }
        }
    }

    fn call(&mut self, req: Req) -> Self::Future {
        assert!(
            self.not_ready.is_empty(),
            "Steer must wait for all services to be ready. Did you forget to call poll_ready()?"
        );

        let idx = self.router.pick(&req, &self.services[..]);
        let cl = &mut self.services[idx];
        self.not_ready.push_back(idx);
        cl.call(req)
    }
}

impl<S, F> Clone for Steer<S, F>
where
    S: Clone,
    F: Clone,
{
    fn clone(&self) -> Self {
        Self {
            router: self.router.clone(),
            services: self.services.clone(),
            not_ready: self.not_ready.clone(),
        }
    }
}

impl<S, F> fmt::Debug for Steer<S, F>
where
    S: fmt::Debug,
    F: fmt::Debug,
{
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        let Self {
            router,
            services,
            not_ready,
        } = self;
        f.debug_struct("Steer")
            .field("router", router)
            .field("services", services)
            .field("not_ready", not_ready)
            .finish()
    }
}
```
And I noticed that the #Req in #MakeBalance's #PhantomData is the #fn(Req), What's difference between the #fn(Req) and #Req.
``` rust
pub struct MakeBalance<S, Req> {
    inner: S,
    _marker: PhantomData<fn(Req)>,
}
```

**Comment by LegNeato** [comment]
I am not super familiar with `Steer`, but the difference between the `tower` version and your implementation is a bit subtle (and perhaps I have it wrong!).

There are two generic `Reqs` in reality, the one passed into `Steer` and one passed into the service `S`. Let's call them  `Req1` and `Req2` respectively. With your implementation, `Steer` is indeed a passthrough. Your `Steer` is implemented for any `Req` that the underlying service `S` can handle--aka **where `Req1` is the same as `Req2`**. With the `tower` `Steer`, it has the same property _plus_ an additional one--the generic `Req` passed to `Steer` can be _different_ than the one passed into `S`--**`Req1` doesn't have to be the same as `Req2`**. So `tower`'s `Steer` is a bit more flexible...it can be a pure passthrough _and/or_ it can take a `Req` that the service `S` can't handle and transform it into something the service can handle.

While for `Steer` it doesn't really matter in practice due to the current implementation, for a library like `tower` the flexibility is desirable as it puts fewer constraints on calling code.

**Comment by Kotodian** [comment]
> I am not super familiar with `Steer`, but the difference between the `tower` version and your implementation is a bit subtle (and perhaps I have it wrong!).
> 
> There are two generic `Reqs` in reality, the one passed into `Steer` and one passed into the service `S`. Let's call them `Req1` and `Req2` respectively. With your implementation, `Steer` is indeed a passthrough. Your `Steer` is implemented for any `Req` that the underlying service `S` can handle--aka **where `Req1` is the same as `Req2`**. With the `tower` `Steer`, it has the same property _plus_ an additional one--the generic `Req` passed to `Steer` can be _different_ than the one passed into `S`--**`Req1` doesn't have to be the same as `Req2`**. So `tower`'s `Steer` is a bit more flexible...it can be a pure passthrough _and/or_ it can take a `Req` that the service `S` can't handle and transform it into something the service can handle.
> 
> While for `Steer` it doesn't really matter in practice due to the current implementation, for a library like `tower` the flexibility is desirable as it puts fewer constraints on calling code.

I understand. thanks for your reply.
