### ISSUE TITLE
Publish `0.5` release

### ISSUE THREAD

**Issue by kpark-hrp** [tower-rs/tower#722]
It has been a while, since the last `tower` release...

I would like to leverage the `&mut` references in `Retry` and batteries included `ExponentialBackoff`. 😃

**Comment by davidpdrsn** [comment]
I believe `master` has breaking changes so it's probably worth seeing if there are other things to fix before doing a new major.

Tower is unfortunately a little understaffed currently I believe. I'm personally busy with axum and tower-http.

**Comment by olix0r** [comment]
There's an [0.5 milestone](https://github.com/tower-rs/tower/issues?q=is%3Aopen+is%3Aissue+milestone%3A0.5) that includes some remaining items. I agree that tower needs some attention/maintenance. We're also a bit saturated with Linkerd work but we may have some more time to help in ~April.

**Comment by LucioFranco** [comment]
I think we can put together a final 0.5 release. I am actively (started as of 2 days ago xD) working on tower 1.0 and its future direction. Mainly focused on the service trait for now.

**Comment by cuviper** [comment]
FWIW, #741 has a breaking change that could be included in a bump.

**Comment by jplatte** [comment]
Same for https://github.com/tower-rs/tower/issues/750, except it's a (small) proposal in an issue, without an implementation.

**Comment by djc** [comment]
Given the lack of resources to drive this forward in a big way, maybe we can get a 0.5 out with a bunch of dependency updates? I would be willing to help out with that if necessary.

**Comment by jplatte** [comment]
This has happened! I don't have the permissions to close it though 😅
