### ISSUE TITLE
RPC notifications

### ISSUE THREAD

**Issue by euclio** [tower-rs/tower#73]
Some RPC protocols (e.g., JSON-RPC, msgpack-RPC) support sending notifications, which are requests (without an ID) that in turn do not have an associated response. Is tower equipped to handle this scenario?

**Comment by carllerche** [comment]
**if** these are truly unattached messages (for example, the client does not issue a subscribe message), then these should be handled outside of the tower abstraction.

For example, a JSON-RPC would provide a tower `Service` and a `Stream` of notifications at two separate APIs.

**Comment by euclio** [comment]
I see. Thank you!
