### ISSUE TITLE
`Reconnect::new()` Generic parameters are redundant 

### ISSUE THREAD

**Issue by artshell** [tower-rs/tower#737]
`Reconnect::new()` Generic parameters are redundant 

[`S, Request>`](https://github.com/tower-rs/tower/blob/bf4ea948346c59a5be03563425a7d9f04aadedf2/tower/src/reconnect/mod.rs#L52)
```rust
    pub fn new<S, Request>(mk_service: M, target: Target) -> Self {
        Reconnect {
            mk_service,
            state: State::Idle,
            target,
            error: None,
        }
    }
```

**Comment by GlenDC** [comment]
Good spot, opened a PR for you at https://github.com/tower-rs/tower/pull/755

**Comment by artshell** [comment]
@GlenDC 

thanks!
