### ISSUE TITLE
`tower::service_fn` docs don't say that you need the `util` flag

### ISSUE THREAD

**Issue by jjant** [tower-rs/tower#743]
See the docs for it: https://docs.rs/tower/latest/tower/fn.service_fn.html.
It doesn't mention that you need to enable `util` which is a bit confusing.

**Comment by GlenDC** [comment]
You’re right. I’ll have a look at this for you!

**Comment by GlenDC** [comment]
Hmm cannot immediately find out why. Master code is also very different doc/attribute wise compared to latest release.

**Comment by GlenDC** [comment]
Ok found how to do it.
https://github.com/tower-rs/tower/pull/754
