### ISSUE TITLE
Add `BoxCloneSyncService` 

### ISSUE THREAD

**Issue by tthebst** [tower-rs/tower#770]
Currently `BoxCloneService` does not implement `Sync` even though the inner Service implements `Sync`. This can be solved by adding a `Sync` bound to the inner service bounds. 

Other projects such as axum also have [this](https://github.com/tokio-rs/axum/blob/5b316ebc64fed4df4d9153b57d7fe2e58cbadb4b/axum/src/box_clone_service.rs) just internally. Might be worth adding it upstream. 

I would be willing to submit a PR for this.

**Comment by tobz** [comment]
@tthebst Yeah, looking at what `axum` does... it seems like that ought to be fine.

If you're willing to submit a PR, that'd be great.

**Comment by GlenDC** [comment]
If you no longer can pick this work up @tthebst in the next weeks do let us know. I can take it over if you wish. Otherwise I’ll leave it with pleasure for you to do, given it was your proposal :)

**Comment by alekseysidorov** [comment]
If you want to use this functionality, I have added it to my [crate](https://docs.rs/tower-http-client/latest/tower_http_client/util/struct.BoxCloneSyncService.html).
