### ISSUE TITLE
use workspace dependencies

### ISSUE THREAD

**Issue by GlenDC** [tower-rs/tower#776]
It's easier to maintain and also easier to see what is used by using workspace dependencies.
For the crate itself it doesn't change much and for the user it works the same.
It's however easier ergonomics for maintainers and contributors.

I can open a PR for you if you want,
pretty easy to transition to it thanks to a tool by luke:
https://github.com/mainmatter/cargo-autoinherit

**Comment by tobz** [comment]
Yeah, I'm familiar with and also use `cargo-autoinherit` myself.

Seems fine to use workspace dependencies. I think, practically, it's not going to be much deduplication at all since `tower` and `tower-test` are the only crates with dependencies, but again... seems fine to do.
