### ISSUE TITLE
Fix dead code warning when default features are turned off.

### ISSUE THREAD

**Issue by tobz** [tower-rs/tower#783]
There's a warning about `Sealed` (in `tower`) not being used when default features are disabled, as seen here: https://github.com/tower-rs/tower/actions/runs/10373855535/job/28719943265#step:5:72

We should fix that.

**Comment by bp7968h** [comment]
Hi @tobz , can this be assigned to me please.

**Comment by tobz** [comment]
Sure, all yours. 👍🏻

**Comment by bp7968h** [comment]
Hi @tobz , I’ve linked the [PR](https://github.com/tower-rs/tower/pull/799). Could you please review it, and your feedback is welcomed!
