### ISSUE TITLE
Consider simplifying NewService

### ISSUE THREAD

**Issue by danburkert** [tower-rs/tower#9]
I'm aware #5 just landed, and I should have brought this up during that review, but hopefully you will indulge me.

Generally, I'm in favor of reducing the number of associated types wherever possible.  In my experience over-use of associated types makes everything more difficult, from implementing and working with the trait in code, to reading the rustdoc for the trait and its implementations.

I propose changing the current definition of `NewService`, which contains 6 associated types, to:

```rust
/// Creates new `Service` values.
pub trait NewService {

    /// The `Service` type created by this factory.
    type Service: Service;

    /// Errors produced while building a service.
    type Error;

    /// The future of the `Service` instance.
    type Future: Future<Item = Self::Service, Error = Self::Error>;

    /// Create and return a new service value asynchronously.
    fn new_service(&self) -> Self::Future;
}
```

I don't think this exact permutation was suggested in #5, but there was some discussion between @carllerche and @withoutboats about associated types of associated types being ambiguous (e.g. `MyNewService::Service::Request` is currently invalid).

In my estimation, reducing the number of associated types will make it easier for beginner and intermediate users of `tower`, up to an including people implementing `NewService` for their own types.  If I understand correctly, the place that the associated types of types issue bites is when writing code which is generic over `NewService` *and* needs to reference a type from the associated `Service`.  Basically, I'm positing that whoever is writing this is an advanced user, and extra `<MyNewService::Service as Service>::Request` syntax isn't That Bad(tm).

**Comment by carllerche** [comment]
`NewService` is gone.
